#!/usr/bin/env python3
"""Aggregate every raw result file into summary tables.

Reads   output/vm-<spec>/raw/*.csv   (one measured value per row)
Writes  output/summary/summary_all.csv   median / min / max / spread of every measurement group
        output/summary/tables/*.csv      one table per question
        output/summary/RESULTS.md        the same tables, readable

Usage: summarize.py <output-dir>
"""
import glob
import os
import re
import sys

import pandas as pd

KEYS = ["spec", "placement", "target", "config", "scale", "experiment", "operation", "variant", "metric", "unit"]
SPEC_ORDER = ["1c512m", "1c1g", "2c2g", "2c4g", "4c8g"]
SCALE_ORDER = ["s", "m", "l"]
SEARCH_OPS = ["point", "exact_common", "exact_rare", "exact_miss", "prefix",
              "contains_common", "contains_rare", "contains_miss", "word_common", "word_rare", "word_miss"]
TARGET_NAME = {"file": "File", "postgres": "PostgreSQL", "opengauss": "openGauss"}
VARIANT_NAME = {"scan": "sequential scan", "memindex": "in-memory index", "noidx": "no index", "btree": "B-tree",
                "noidx_serial": "no index, parallel query off", "noidx_dop3": "no index, parallel query on",
                "trgm": "trigram GIN", "fts": "full-text GIN", "safe": "rewrite + fsync", "nofsync": "rewrite, no fsync",
                "heap": "heap", "ustore": "Ustore (in-place)"}
# A "does this machine carry the business" target for the spec ladder; the raw numbers are in the
# tables, so a different target can be applied without re-running anything.
SLO_P95_MS = 50.0


def load(root):
    frames = []
    for path in sorted(glob.glob(os.path.join(root, "vm-*", "raw", "*.csv"))):
        if os.path.basename(path).startswith("_"):
            continue
        frame = pd.read_csv(path, keep_default_na=False, dtype=str)
        frames.append(frame)
    df = pd.concat(frames, ignore_index=True)
    df["value"] = pd.to_numeric(df["value"], errors="coerce")
    df["rep"] = pd.to_numeric(df["rep"], errors="coerce").fillna(0).astype(int)
    return df


def summarize(df):
    s = df.groupby(KEYS, sort=False)["value"].agg(
        n="count", median="median", min="min", max="max", mean="mean", std="std").reset_index()
    s["cv_pct"] = (s["std"] / s["mean"] * 100).where((s["n"] > 1) & (s["mean"] != 0))
    return s


def method(row):
    return f"{TARGET_NAME.get(row['target'], row['target'])}: {VARIANT_NAME.get(row['variant'], row['variant'])}"


def fmt(v):
    """Three significant digits; integers stay integers."""
    if isinstance(v, str):
        return v
    if v is None or pd.isna(v):
        return "–"
    if float(v).is_integer() and abs(v) < 1e15:
        return f"{int(v):,}"
    a = abs(v)
    if a >= 100:
        return f"{v:,.0f}"
    if a >= 10:
        return f"{v:.1f}"
    if a >= 1:
        return f"{v:.2f}"
    if a >= 0.01:
        return f"{v:.3f}"
    return f"{v:.5f}"


def md_table(df):
    cols = [str(c) for c in df.columns]
    lines = ["| " + " | ".join(cols) + " |", "|" + "|".join("---" for _ in cols) + "|"]
    for _, row in df.iterrows():
        lines.append("| " + " | ".join(fmt(v) for v in row.tolist()) + " |")
    return "\n".join(lines)


def ordered(df, column, order):
    known = [v for v in order if v in set(df[column])]
    rest = [v for v in df[column].unique() if v not in known]
    return df.assign(**{column: pd.Categorical(df[column], known + rest, ordered=True)}).sort_values(column)


def pick(s, **filters):
    out = s
    for key, want in filters.items():
        out = out[out[key].isin(want)] if isinstance(want, (list, tuple, set)) else out[out[key] == want]
    return out


def pivot(df, index, columns, value="median", index_order=None, column_order=None):
    if df.empty:
        return pd.DataFrame()
    p = df.pivot_table(index=index, columns=columns, values=value, aggfunc="first", sort=False)
    if index_order:
        p = p.reindex([i for i in index_order if i in p.index] + [i for i in p.index if i not in index_order])
    if column_order:
        p = p[[c for c in column_order if c in p.columns] + [c for c in p.columns if c not in column_order]]
    p.columns = [str(c) if not isinstance(c, tuple) else " / ".join(map(str, c)) for c in p.columns]
    return p.reset_index()


class Report:
    def __init__(self, out_dir):
        self.out_dir = out_dir
        self.parts = ["# Results\n", "Generated by `Codes/analysis/summarize.py` from the raw measurements. "
                      "Unless stated otherwise a cell is the median of the repetitions; times are milliseconds.\n"]
        os.makedirs(os.path.join(out_dir, "tables"), exist_ok=True)

    def section(self, title, note=""):
        self.parts.append(f"\n## {title}\n")
        if note:
            self.parts.append(note + "\n")

    def table(self, name, df, caption=""):
        if df is None or df.empty:
            return
        df.to_csv(os.path.join(self.out_dir, "tables", name + ".csv"), index=False)
        if caption:
            self.parts.append(f"\n**{caption}**\n")
        self.parts.append(md_table(df) + "\n")

    def write(self):
        with open(os.path.join(self.out_dir, "RESULTS.md"), "w", encoding="utf-8") as f:
            f.write("\n".join(self.parts))


METHOD_ORDER = ["File: sequential scan", "File: in-memory index", "PostgreSQL: no index", "PostgreSQL: B-tree",
                "PostgreSQL: trigram GIN", "PostgreSQL: full-text GIN", "openGauss: no index", "openGauss: B-tree",
                "openGauss: full-text GIN"]
PARALLEL = ["noidx_serial", "noidx_dop3"]   # extra runs that only change the parallel-query setting


def dataset_tables(rep, s):
    prep = pick(s, experiment="prep")
    if prep.empty:
        return
    rep.section("Dataset", "IMDb non-commercial datasets. s / m / l are nested 1 % / 10 % / 100 % samples of the real rows.")
    rows = pick(prep, metric="rows", variant=SCALE_ORDER)
    size = pick(prep, metric="file_bytes").assign(median=lambda d: d["median"] / 1048576)
    t = pivot(rows, "operation", "variant", column_order=SCALE_ORDER).rename(
        columns={"operation": "table", "s": "rows s", "m": "rows m", "l": "rows l"})
    t2 = pivot(size, "operation", "variant", column_order=SCALE_ORDER).rename(
        columns={"operation": "table", "s": "MiB s", "m": "MiB m", "l": "MiB l"})
    rep.table("dataset", t.merge(t2, on="table"))


def search_tables(rep, s):
    search = pick(s, experiment="search", spec="4c8g")
    if search.empty:
        return
    search = search.assign(method=search.apply(method, axis=1))
    rep.section("Retrieval: file versus DBMS",
                "VM 4 CPU / 8 GiB, client inside the VM. Latency seen by the caller, including reading every result row.")
    tuned = search[search["config"].isin(["na", "tuned"]) & ~search["variant"].isin(PARALLEL)]
    for scale in SCALE_ORDER:
        lat = pick(tuned, metric="latency_ms", scale=scale)
        lat = lat[lat["operation"] != "build"]
        rows = pick(tuned, metric="rows", scale=scale, variant=["scan", "noidx", "fts"]).groupby("operation")["median"].first()
        t = pivot(lat, "operation", "method", index_order=SEARCH_OPS, column_order=METHOD_ORDER)
        if t.empty:
            continue
        t.insert(1, "rows returned", t["operation"].map(rows))
        rep.table(f"search_latency_{scale}", t, f"Scale {scale}: median latency (ms)")

    build = pick(tuned, operation="build")
    if not build.empty:
        rep.table("file_index_build", pivot(build, "scale", "metric", index_order=SCALE_ORDER),
                  "Cost of the in-memory file index (paid at every program start)")

    server = pick(search, metric="server_ms", scale="l", config="tuned")
    if not server.empty:
        t = pivot(server, "operation", "method", index_order=SEARCH_OPS, column_order=METHOD_ORDER)
        rep.table("search_server_time_l", t, "Scale l: execution time inside the engine (EXPLAIN ANALYZE, ms)")

    par = pick(search, metric="latency_ms", scale="l", config="tuned", target=["postgres", "opengauss"],
               variant=["noidx"] + PARALLEL)
    if set(PARALLEL) & set(par["variant"]):
        rep.table("search_parallel_query_l", pivot(par, "operation", "method", index_order=SEARCH_OPS),
                  "Scale l, full scans: effect of parallel query (PostgreSQL uses 2 workers by default; "
                  "openGauss runs serially unless query_dop is raised, here to 3) (ms)")

    # Result equality: every method must return the same rows for the same query.
    chk = pick(search[search["config"].isin(["na", "tuned"])], metric=["rows", "id_sum"])
    chk = chk[~chk["variant"].isin(["fts"]) & (chk["operation"] != "build")]
    agree = chk.groupby(["scale", "operation", "metric"])["median"].agg(methods="count", distinct="nunique").reset_index()
    agree["identical"] = agree["distinct"].eq(1).map({True: "yes", False: "NO"})
    agree = ordered(agree, "scale", SCALE_ORDER)
    rep.table("search_result_check", pd.DataFrame({
        "checks": [len(agree)], "methods compared (max)": [agree["methods"].max()],
        "identical": [int((agree["identical"] == "yes").sum())], "different": [int((agree["identical"] == "NO").sum())]}),
        "Result check: row count and id checksum of every query, compared across all methods")
    if (agree["identical"] == "NO").any():
        rep.table("search_result_mismatch", agree[agree["identical"] == "NO"], "Mismatches")

    default = pick(search, metric="latency_ms", scale="l", target=["postgres", "opengauss"], variant=["noidx", "btree"])
    if "default" in set(default["config"]):
        default = default.assign(column=default["method"] + " (" + default["config"] + ")")
        rep.table("search_default_vs_tuned_l", pivot(default, "operation", "column", index_order=SEARCH_OPS),
                  "Scale l: image default settings versus settings aligned for the spec (ms)")


def update_tables(rep, s):
    upd = pick(s, experiment="update", spec="4c8g")
    if upd.empty:
        return
    upd = upd.assign(method=upd.apply(method, axis=1))
    rep.section("Bulk update: file versus DBMS",
                "Replace every \"T\" with \"Ttt\" in person names. broad = all rows containing T; narrow = ten given rows.")
    tuned = upd[upd["config"].isin(["na", "tuned"])]
    lat = pick(tuned, metric="latency_ms")
    t = lat.assign(case=lat["scale"] + " " + lat["operation"])
    order = [f"{sc} {rule}" for sc in SCALE_ORDER for rule in ("broad", "narrow")]
    rep.table("update_latency", pivot(t, "case", "method", index_order=order).rename(columns={"case": "scale and rule"}),
              "Median latency (ms)")

    chk = pick(tuned, metric=["rows_changed", "check_rows", "check_name_bytes", "check_rows_with_Ttt"])
    agree = chk.groupby(["scale", "operation", "metric"])["median"].agg(methods="count", distinct="nunique").reset_index()
    rep.table("update_result_check", pd.DataFrame({
        "checks": [len(agree)], "methods compared (max)": [agree["methods"].max()],
        "identical": [int((agree["distinct"] == 1).sum())], "different": [int((agree["distinct"] != 1).sum())]}),
        "Result check: rows changed, row count, total name bytes and rows containing Ttt, compared across all methods")

    bloat = pick(tuned, metric=["heap_before_mb", "heap_after_mb", "heap_after_vacuum_mb", "vacuum_ms"], scale="l")
    if not bloat.empty:
        b = bloat.assign(case=bloat["operation"] + ", " + bloat["method"])
        rep.table("update_space_l", pivot(b, "case", "metric", column_order=[
            "heap_before_mb", "heap_after_mb", "heap_after_vacuum_mb", "vacuum_ms"]),
            "Scale l: table size around the update (MiB) and VACUUM time (ms)")

    default = pick(upd, metric="latency_ms", scale="l", operation="broad", variant="heap")
    if "default" in set(default["config"]):
        rep.table("update_default_vs_tuned_l", pivot(default, "method", "config"),
                  "Scale l, broad update: default versus aligned settings (ms)")


def storage_tables(rep, s):
    setup = pick(s, experiment=["setup", "index"], spec="4c8g", config="tuned")
    if setup.empty:
        return
    rep.section("Loading and storage cost", "VM 4 CPU / 8 GiB, aligned settings.")
    setup = setup.assign(db=setup["target"].map(TARGET_NAME))
    load = pick(setup, experiment="setup", metric=["load_ms", "build_ms", "heap_mb", "total_mb"], scale="l")
    load = load.assign(item=load["operation"] + " " + load["metric"])
    rep.table("load_and_size_l", pivot(load, "item", "db"), "Scale l: COPY time, primary-key build time (ms) and sizes (MiB)")
    idx = pick(setup, experiment="index", scale="l", metric=["build_ms", "index_mb", "supported"])
    idx = idx.assign(item=idx["variant"].map(VARIANT_NAME).fillna(idx["variant"]) + " " + idx["metric"])
    rep.table("secondary_indexes_l", pivot(idx, "item", "db"),
              "Scale l: secondary indexes on titles(primary_title) (supported: 1 = yes, 0 = cannot be built)")
    dbsize = pick(setup, metric="size_mb")
    rep.table("database_size", pivot(dbsize, "scale", "db", index_order=SCALE_ORDER), "Database size after loading (MiB)")


def load_tables(rep, s):
    load = pick(s, experiment="load")
    if load.empty:
        return
    rep.section("Concurrent load: PostgreSQL versus openGauss",
                "Full data set, aligned settings, clients on the host. Median of the rounds; [min – max] shows the spread.")
    load = load.assign(db=load["target"].map(TARGET_NAME), clients=load["variant"].str[1:].astype(int))
    for spec in [sp for sp in SPEC_ORDER if sp in set(load["spec"])]:
        for workload in ("read", "mixed"):
            part = pick(load, spec=spec, operation=workload)
            if part.empty:
                continue
            rows = []
            for clients in sorted(part["clients"].unique()):
                row = {"clients": clients}
                for db in ("PostgreSQL", "openGauss"):
                    g = part[(part["clients"] == clients) & (part["db"] == db)].set_index("metric")
                    if g.empty:
                        continue
                    tp = g.loc["throughput_ops"]
                    row[f"{db} ops/s"] = f"{tp['median']:,.0f} [{tp['min']:,.0f} – {tp['max']:,.0f}]"
                    for m in ("p50_ms", "p95_ms", "p99_ms"):
                        row[f"{db} {m[:-3]}"] = g.loc[m, "median"]
                    row[f"{db} errors"] = g.loc["errors", "max"]
                    if "server_cpu_cores" in g.index:
                        row[f"{db} CPU cores"] = g.loc["server_cpu_cores", "median"]
                rows.append(row)
            rep.table(f"load_{spec}_{workload}", pd.DataFrame(rows), f"VM {spec}, workload {workload}")


def reliability_tables(rep, s, df):
    rel = s[s["experiment"].isin(["lost_update", "unique_race", "crash", "conn_limit", "errors", "heavy", "soak"])]
    if rel.empty:
        return
    rep.section("Reliability", "Each test ends by inspecting the stored data, not the reply the client received.")
    rel = rel.assign(who=rel["target"].map(TARGET_NAME))

    lost = pick(rel, experiment="lost_update", metric=["expected", "actual", "lost", "retries", "throughput_ops"])
    if not lost.empty:
        lost = lost.assign(case=lost["who"] + " (" + lost["spec"] + "): " + lost["variant"])
        rep.table("lost_update", pivot(lost, "case", "metric", column_order=["expected", "actual", "lost", "retries", "throughput_ops"]),
                  "8 concurrent clients each add 1 to the same counter (median of 3 runs)")

    race = pick(rel, experiment="unique_race")
    if not race.empty:
        rep.table("unique_race", pivot(race, "who", "metric", column_order=[
            "rounds", "accepted", "rejected_duplicate", "other_errors", "rows_in_table"]),
            "16 clients insert the same key at the same instant, 300 rounds")

    crash = df[df["experiment"] == "crash"].assign(who=lambda d: d["target"].map(TARGET_NAME))
    load_kill = crash[(crash["operation"] == "write_load") & (crash["variant"] == "kill9")]
    if not load_kill.empty:
        t = load_kill.pivot_table(index="who", columns="metric", values="value", aggfunc="sum", sort=False)
        t.insert(0, "kills", load_kill.groupby("who", sort=False)["rep"].nunique())
        order = ["kills", "acknowledged_commits", "acknowledged_but_missing", "partial_transactions",
                 "unbalanced_transactions", "committed_without_ack"]
        rep.table("crash_under_write_load", t[[c for c in order if c in t.columns]].reset_index().rename(columns={"who": "system"}),
                  "Server killed (kill -9) under write load: totals over all kills. A commit is \"acknowledged\" once "
                  "the client saw COMMIT return; committed_without_ack are commits the server finished but could not report")
    bulk = crash[(crash["operation"] == "bulk_update") & (crash["variant"] != "recovery")]
    if not bulk.empty:
        bulk = bulk.assign(case=bulk["who"] + ": " + bulk["variant"].map(
            {"inplace": "overwrite in place", "safe": "temp file + rename", "kill9": "one UPDATE"}).fillna(bulk["variant"]))
        t = bulk.pivot_table(index="case", columns="metric", values="value", aggfunc="max", sort=False)
        order = ["kill_landed", "rows_before", "rows_after", "rows_lost", "rows_with_Ttt_before", "rows_with_Ttt_after",
                 "truncated_last_line", "leftover_temp_bytes"]
        rep.table("crash_during_bulk_update", t[[c for c in order if c in t.columns]].reset_index(),
                  "Writer killed in the middle of a bulk update (worst repetition). rows_with_Ttt_after above the "
                  "\"before\" value means the update was left half-applied")
    ready = pick(rel, experiment="crash", metric="time_to_ready_ms")
    if not ready.empty:
        rep.table("crash_recovery_time", ready[["who", "operation", "n", "median", "min", "max"]].rename(
            columns={"who": "system", "operation": "killed during", "n": "runs"}), "Time from restart until queries are answered (ms)")

    conn = pick(rel, experiment="conn_limit")
    if not conn.empty:
        rep.table("connection_limit", pivot(conn, "who", "metric"), "Opening connections until refused")

    heavy = s[s["experiment"].isin(["heavy"])]
    if not heavy.empty:
        heavy = heavy.assign(case=heavy["target"].map(TARGET_NAME) + " (" + heavy["spec"] + ")")
        rep.table("heavy_queries", pivot(heavy, ["operation", "metric"], "case"), "Heavy analytical queries on the full data")

    soak = pick(rel, experiment="soak")
    if not soak.empty:
        rep.table("soak", pivot(soak, "metric", "who"), "Sustained mixed load, 16 clients")

    notes = df[(df["experiment"].isin(["errors", "conn_limit"])) & (df["note"] != "")]
    if not notes.empty:
        # The openGauss JDBC driver prefixes every message with masked socket addresses; drop that part.
        notes = notes.assign(note=notes["note"].map(lambda m: re.sub(r"\[\*\.\*\.[^\]]*\] ", "", m)))
        t = notes.assign(db=notes["target"].map(TARGET_NAME)).pivot_table(
            index="operation", columns="db", values="note", aggfunc="first", sort=False).reset_index()
        rep.table("error_messages", t.rename(columns={"operation": "situation"}), "What each system answers (SQLSTATE: message)")


def ladder_tables(rep, s, df):
    lad = s[s["experiment"].isin(["ladder", "ladder_heavy"])]
    if lad.empty:
        return
    rep.section("Server requirements: the spec ladder",
                "The whole VM is resized to each spec. Load: 16 clients, 80 % reads / 20 % writes, full data set. "
                f"\"meets target\" = started, no failed request, p95 ≤ {SLO_P95_MS:.0f} ms, still running afterwards.\n\n"
                "Settings: *default* = the instance exactly as it was installed on the 4 CPU / 8 GiB machine, moved to "
                "the smaller machine unchanged; *tuned* = memory settings sized for the machine at hand. *fresh install* "
                "tests only whether a brand-new instance initialises and starts on that machine. The distinction matters "
                "for openGauss, whose installer picks shared_buffers by machine size (32 MB on 1 GiB, 1 GB on 8 GiB; see "
                "`vm-1c1g/logs/settings_og_fresh_install.txt`), while PostgreSQL always installs with 128 MB.")
    rows = []
    for spec in [sp for sp in SPEC_ORDER if sp in set(lad["spec"])]:
        for target in ("postgres", "opengauss"):
            fresh = pick(lad, spec=spec, target=target, operation="fresh_install").set_index("metric")["median"]
            for config in ("default", "tuned"):
                g = pick(lad, spec=spec, target=target, config=config)
                if g.empty:
                    continue
                v = {(r.operation, r.metric): r.median for r in g.itertuples()}
                started = v.get(("start", "available"), 0) == 1
                errors = v.get(("mixed", "errors"))
                p95 = v.get(("mixed", "p95_ms"))
                alive = v.get(("survive", "still_running"), 0) == 1
                ok = bool(started and alive and errors == 0 and p95 is not None and p95 <= SLO_P95_MS)
                rows.append({
                    "spec": spec, "system": TARGET_NAME[target], "settings": config,
                    "fresh install": "ok" if fresh.get("available", 0) == 1 else "FAILS",
                    "starts": "yes" if started else "NO",
                    "ready (ms)": v.get(("start", "time_to_ready_ms")),
                    "idle memory (MiB)": v.get(("start", "idle_mem_mb")),
                    "ops/s": v.get(("mixed", "throughput_ops")),
                    "p95 (ms)": p95, "p99 (ms)": v.get(("mixed", "p99_ms")),
                    "failed requests": errors,
                    "sort all (ms)": v.get(("sort_all_titles", "latency_ms")),
                    "join+agg (ms)": v.get(("join_aggregate", "latency_ms")),
                    "peak memory (MiB)": v.get(("survive", "server_mem_peak_mb")),
                    "OOM kills": v.get(("survive", "vm_oom_kills"), v.get(("start", "vm_oom_kills"))),
                    "meets target": "yes" if ok else "no"})
    table = pd.DataFrame(rows)
    rep.table("spec_ladder", table)
    if not table.empty:
        lowest = (table[table["meets target"] == "yes"].groupby(["system", "settings"], sort=False)["spec"]
                  .agg(lambda x: min(x, key=SPEC_ORDER.index)).reset_index().rename(columns={"spec": "smallest spec that meets the target"}))
        rep.table("spec_ladder_minimum", lowest, "Smallest machine that meets the target")
    machine = pick(lad, operation="machine")
    if not machine.empty:
        rep.table("spec_ladder_machine", pivot(machine, "spec", "metric", index_order=SPEC_ORDER),
                  "Memory of the bare VM (Linux + Docker, no database), MiB")
    fails = df[(df["experiment"] == "ladder") & (df["metric"] == "failure_log")]
    fails = fails.assign(note=fails["note"].where(fails["note"] != "", "(the server process exits without writing a message; "
                                                  "see logs/diagnosis_og_start.txt of that spec)"))
    if not fails.empty:
        rep.table("spec_ladder_failures", fails.assign(system=fails["target"].map(TARGET_NAME))[
            ["spec", "system", "config", "operation", "note"]], "Why it did not start (last log lines)")


def quality_table(rep, s):
    q = s[(s["n"] >= 3) & s["metric"].isin(["latency_ms", "throughput_ops"]) & (s["cv_pct"] > 20)]
    rep.section("Measurement quality",
                "Groups of at least three repetitions whose coefficient of variation exceeds 20 %. "
                "Sub-millisecond operations are noisy by nature; anything else listed here deserves a re-run.")
    total = int(((s["n"] >= 3) & s["metric"].isin(["latency_ms", "throughput_ops"])).sum())
    rep.parts.append(f"{len(q)} of {total} groups are above the threshold.\n")
    if not q.empty:
        rep.table("noisy_groups", q[["spec", "target", "config", "scale", "experiment", "operation", "variant",
                                     "metric", "n", "median", "min", "max", "cv_pct"]].sort_values("cv_pct", ascending=False).head(40))


def main():
    root = sys.argv[1]
    out_dir = os.path.join(root, "summary")
    os.makedirs(out_dir, exist_ok=True)
    df = load(root)
    s = summarize(df)
    s.to_csv(os.path.join(out_dir, "summary_all.csv"), index=False)
    rep = Report(out_dir)
    dataset_tables(rep, s)
    search_tables(rep, s)
    update_tables(rep, s)
    storage_tables(rep, s)
    load_tables(rep, s)
    reliability_tables(rep, s, df)
    ladder_tables(rep, s, df)
    quality_table(rep, s)
    rep.write()
    print(f"summarised {len(df)} measurements in {len(s)} groups -> {out_dir}")


if __name__ == "__main__":
    main()
