package dbbench.data;

import dbbench.util.Args;
import dbbench.util.ResultLog;
import dbbench.util.Tsv;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.Properties;
import java.util.StringJoiner;
import java.util.zip.GZIPInputStream;

/**
 * Converts the raw IMDb dumps into the cleaned files used by every experiment.
 *
 * <p>Three nested samples are produced from the real data: s = 1 %, m = 10 %, l = 100 %. A row is
 * kept when a hash of its numeric id falls below the percentage, so the samples are deterministic,
 * spread evenly over the whole id range, and never contain invented rows. Malformed rows (the dumps
 * contain a few with a missing tab) are dropped and counted.
 */
public final class PrepareData {
    private static final String[] SCALES = {"s", "m", "l"};
    private static final int[] PERCENT = {1, 10, 100};

    private PrepareData() {}

    /** Turns the fields of one raw row into a cleaned line, or returns null if the row is malformed. */
    private interface Cleaner {
        String clean(int id, String[] f);
    }

    /** Sees every kept row; used to collect ids for the workload definition. */
    private interface Observer {
        void kept(int scale, int id, String[] f);
    }

    public static void run(Args a) throws IOException {
        Path raw = Path.of(a.get("raw-dir")), out = Path.of(a.get("out-dir"));
        Files.createDirectories(out);
        Properties[] meta = {new Properties(), new Properties(), new Properties()};

        try (ResultLog log = new ResultLog(a, "file")) {
            IntList[] titleIds = lists();
            convert(raw.resolve("title.basics.tsv.gz"), out, "titles", 9, PrepareData::cleanTitle,
                    (s, id, f) -> titleIds[s].add(id), meta, log);

            IntList[] namesWithT = lists();
            convert(raw.resolve("name.basics.tsv.gz"), out, "people", 6, PrepareData::cleanPerson,
                    (s, id, f) -> { if (f[1].indexOf('T') >= 0) namesWithT[s].add(id); }, meta, log);

            IntList[] ratingIds = lists();
            convert(raw.resolve("title.ratings.tsv.gz"), out, "ratings", 3, PrepareData::cleanRating,
                    (s, id, f) -> ratingIds[s].add(id), meta, log);

            for (int s = 0; s < SCALES.length; s++) {
                meta[s].setProperty("point_ids", spread(titleIds[s], 5));
                meta[s].setProperty("narrow_ids", spread(namesWithT[s], 10));
                meta[s].setProperty("people_with_T", Integer.toString(namesWithT[s].size));
                meta[s].setProperty("counter_rating_id", spread(ratingIds[s], 1));
                try (OutputStream os = Files.newOutputStream(out.resolve("meta_" + SCALES[s] + ".properties"))) {
                    meta[s].store(os, "Workload constants derived from the data; generated by PrepareData");
                }
                log.add("prep", "people", SCALES[s], 0, "rows_with_T", namesWithT[s].size, "rows");
            }
        }
    }

    private static void convert(Path gz, Path outDir, String table, int fieldCount, Cleaner cleaner,
                                Observer observer, Properties[] meta, ResultLog log) throws IOException {
        long t0 = System.nanoTime();
        long[] rows = new long[SCALES.length];
        long rawRows = 0, malformed = 0;
        BufferedWriter[] writers = new BufferedWriter[SCALES.length];
        Path[] paths = new Path[SCALES.length];
        try (BufferedReader in = new BufferedReader(new InputStreamReader(
                new GZIPInputStream(Files.newInputStream(gz), 1 << 16), StandardCharsets.UTF_8), 1 << 20)) {
            for (int s = 0; s < SCALES.length; s++) {
                paths[s] = outDir.resolve(table + "_" + SCALES[s] + ".tsv");
                writers[s] = new BufferedWriter(Files.newBufferedWriter(paths[s], StandardCharsets.UTF_8), 1 << 20);
            }
            String[] f = new String[fieldCount + 1];
            in.readLine(); // header
            String line;
            while ((line = in.readLine()) != null) {
                rawRows++;
                String cleaned = null;
                int id = -1;
                if (Tsv.split(line, f) == fieldCount && f[0].length() > 2) {
                    try {
                        id = Integer.parseInt(f[0].substring(2)); // "tt0000001" / "nm0000001" -> 1
                        cleaned = cleaner.clean(id, f);
                    } catch (NumberFormatException e) {
                        cleaned = null;
                    }
                }
                if (cleaned == null) {
                    malformed++;
                    continue;
                }
                int bucket = bucket(id);
                for (int s = 0; s < SCALES.length; s++) {
                    if (bucket < PERCENT[s]) {
                        writers[s].write(cleaned);
                        writers[s].write('\n');
                        rows[s]++;
                        observer.kept(s, id, f);
                    }
                }
            }
        } finally {
            for (BufferedWriter w : writers) if (w != null) w.close();
        }
        double seconds = (System.nanoTime() - t0) / 1e9;
        System.out.printf("%s: raw=%d malformed=%d kept s/m/l=%d/%d/%d (%.1fs)%n",
                table, rawRows, malformed, rows[0], rows[1], rows[2], seconds);
        log.add("prep", table, "raw", 0, "rows", rawRows, "rows");
        log.add("prep", table, "raw", 0, "malformed_rows", malformed, "rows");
        for (int s = 0; s < SCALES.length; s++) {
            meta[s].setProperty(table + "_rows", Long.toString(rows[s]));
            log.add("prep", table, SCALES[s], 0, "rows", rows[s], "rows");
            log.add("prep", table, SCALES[s], 0, "file_bytes", Files.size(paths[s]), "bytes");
        }
    }

    /** Deterministic 0..99 bucket of an id (integer hash, so samples are not biased by id order). */
    static int bucket(int id) {
        int h = id * 0x9E3779B1;
        h ^= h >>> 15;
        h *= 0x85EBCA6B;
        h ^= h >>> 13;
        return (h & 0x7fffffff) % 100;
    }

    // tconst, titleType, primaryTitle, originalTitle, isAdult, startYear, endYear, runtimeMinutes, genres
    private static String cleanTitle(int id, String[] f) {
        if (!(f[4].equals("0") || f[4].equals("1"))) return null;
        if (!intOrNull(f[5], 4) || !intOrNull(f[6], 4) || !intOrNull(f[7], 9)) return null;
        return join(id, f, 9);
    }

    // nconst, primaryName, birthYear, deathYear, primaryProfession, knownForTitles
    private static String cleanPerson(int id, String[] f) {
        if (!intOrNull(f[2], 4) || !intOrNull(f[3], 4)) return null;
        return join(id, f, 6);
    }

    // tconst, averageRating, numVotes
    private static String cleanRating(int id, String[] f) {
        Double.parseDouble(f[1]);
        if (!intOrNull(f[2], 9)) return null;
        return join(id, f, 3);
    }

    private static boolean intOrNull(String s, int maxDigits) {
        if (s.equals(Tsv.NULL)) return true;
        if (s.isEmpty() || s.length() > maxDigits) return false;
        for (int i = 0; i < s.length(); i++) if (s.charAt(i) < '0' || s.charAt(i) > '9') return false;
        return true;
    }

    private static String join(int id, String[] f, int n) {
        StringBuilder sb = new StringBuilder(96).append(id);
        for (int i = 1; i < n; i++) sb.append('\t').append(Tsv.escape(f[i]));
        return sb.toString();
    }

    /** Picks {@code n} ids evenly spread over the sorted list (n = 1 gives the median). */
    private static String spread(IntList list, int n) {
        int[] sorted = Arrays.copyOf(list.data, list.size);
        Arrays.sort(sorted);
        StringJoiner sj = new StringJoiner(",");
        for (int i = 0; i < n && sorted.length > 0; i++) {
            sj.add(Integer.toString(sorted[(int) ((2L * i + 1) * sorted.length / (2L * n))]));
        }
        return sj.toString();
    }

    private static IntList[] lists() {
        return new IntList[] {new IntList(), new IntList(), new IntList()};
    }

    private static final class IntList {
        int[] data = new int[1 << 16];
        int size;

        void add(int v) {
            if (size == data.length) data = Arrays.copyOf(data, size * 2);
            data[size++] = v;
        }
    }
}
